#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Used for various Phabricator scripts...
export PHABRICATOR_ENV=custom/myconfig

pushd $OPENSHIFT_GEAR_DIR/repo

git clone --recursive git://github.com/facebook/phabricator.git
git clone --recursive git://github.com/facebook/libphutil.git
git clone --recursive git://github.com/facebook/arcanist.git

# An annoying way to deal with config files...
# Phabricator (and libphutil) is cloned on each deploy, which is good for two
# reasons.
# 1) It means every time we push, OpenShift will pull in upstream's changes.
#    (Upstream is very active)
# 2) It forces us to have to work hard to diverge from upstream.
#    And that's exactly what we're doing with our config file -- it's custom.
if [[ ! -d "./phabricator/conf/custom" ]]; then
  mkdir ./phabricator/conf/custom
fi

mv ./misc/myconfig.conf.php ./phabricator/conf/custom/

if [[ ! -d "./pygments" ]]; then
  virtualenv pygments
  source ./pygments/bin/activate
  easy_install Pygments
fi

# Up the db schema.
$OPENSHIFT_GEAR_DIR/repo/phabricator/bin/storage upgrade --force

# Everything hates me.
ln -svf $OPENSHIFT_GEAR_DIR/repo/phabricator/webroot/* $OPENSHIFT_GEAR_DIR/repo/php/

popd
